### ISSUE TITLE
taskcluster: change origin/project/owner/revision extraction for tools.taskcluster.net

### ISSUE THREAD

**Issue by trink** [mozilla-services/lua_sandbox_extensions#464]
The URL is currently split to generate the following
origin: tools.taskcluster.net
project: hg-push
projectOwner: hooks
revision: &lt;hook name&gt;
See #445

@srfraser to define desired behavior

**Comment by srfraser** [comment]
So it's a case of treating urls such as `https://tools.taskcluster.net/hooks/#project-releng/cron-task-releases-mozilla-beta` differently in the `md_source` parser, as it doesn't contain the same elements as an hg/github repo url.

For tools.taskcluster.net urls, placing the entire thing in the `origin` field is probably the closest fit for this, as the hook is the originator of the task graph. 

The task owner's email address is present in `metadata.owner` and should probably be used rather than trying to parse the url.

`payload.env.GECKO_HEAD_REPOSITORY` would be the best place to find the source repository used, and so what the project is. 

The revision for hooks is usually `default`

**Comment by trink** [comment]
not seeing GECKO_HEAD_REPOSITORY in payload though should it be the heads array in the nested json?

```json
{
  "env": {
    "PROJECT": "try",
    "LEVEL": "1",
    "REPO_URL": "https:\/\/hg.mozilla.org\/try",
    "PULSE_MESSAGE": "{\"_meta\":{\"exchange\":\"exchange\/hgpushes\/v2\",\"routing_key\":\"try\",\"sent\":\"2019-09-29T23:39:55.438441\",\"serializer\":\"json\"},\"payload\":{\"data\":{\"heads\":[\"4f6b69ed33ffed94640e7b85bc0acdd663176147\"],\"pushlog_pushes\":[{\"push_full_json_url\":\"https:\/\/hg.mozilla.org\/try\/json-pushes?version=2&full=1&startID=428832&endID=428833\",\"push_json_url\":\"https:\/\/hg.mozilla.org\/try\/json-pushes?version=2&startID=428832&endID=428833\",\"pushid\":428833,\"time\":1569800352,\"user\":\"echen@mozilla.com\"}],\"repo_url\":\"https:\/\/hg.mozilla.org\/try\",\"source\":\"serve\"},\"type\":\"changegroup.1\"}}"
  },
  "image": {
    "type": "indexed-image",
    "namespace": "ci.cache.level-3.docker-images.v2.hg-push.hash.5d88330fd2c4308906720c592564199812354b443448d0bac5e3bdcb28168999",
    "path": "public\/image.tar.zst"
  },
  "maxRunTime": 600,
  "features": {
    "taskclusterProxy": true
  }
}
```

**Comment by trink** [comment]
owner is metadata.owner
projectOwner should probably just be NULL instead of hooks 

so for the case above you would want to see something like this?
origin: tools.taskcluster.net/hooks/hg-push/try
project: try
projectOwner: NULL
revision: 4f6b69ed33ffed94640e7b85bc0acdd663176147

**Comment by srfraser** [comment]
Yes, that works for me.

**Comment by trink** [comment]
#467
